# Generated by Django 3.2.12 on 2022-04-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220424_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='fridge',
            name='ingredients',
            field=models.ManyToManyField(to='accounts.Ingredient'),
        ),
    ]
