# Generated by Django 3.2.12 on 2022-04-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220424_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='description',
        ),
        migrations.AlterField(
            model_name='fridge',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
