# Generated by Django 3.2.12 on 2022-04-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220424_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='fridges',
            field=models.ManyToManyField(to='accounts.Fridge'),
        ),
    ]
