# Generated by Django 3.2.12 on 2022-05-03 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220424_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridge',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Fridge',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
