# Generated by Django 3.0.9 on 2022-05-12 23:25

from django.conf import settings
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipeTitle', models.CharField(max_length=200)),
                ('cookTime', models.IntegerField()),
                ('ingredients', django_mysql.models.ListCharField(models.CharField(max_length=45), max_length=1000, size=20)),
                ('recipeLink', models.CharField(max_length=500)),
                ('recipeImages', models.CharField(max_length=500)),
                ('favorite', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
